<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ page import="java.sql.*" %>
    <%@ page import="databaseConnection.DbConnection" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Parent form</title>
 <link rel="stylesheet" type="text/css" href="view.css" media="all">
</head>
<body id="main_body" >
	
	<div id="form_container">
	
		<h1><a>Parent Login info</a></h1>
		<form id="form_1125809" class="appnitro"  method="post" action="AddParentInfo">
					<div class="form_description">
			<h2>Parent Login Info</h2>
		</div>						
			<ul >
						<select name = "StudentName" >
						<li id ="li_0" >
<label class="description" for="element_0">Student Name</label>
<span>
<% 
PreparedStatement con=null;
//ResultSet rs=null;

try
{
     //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
     //con=DriverManager.getConnection("jdbc:odbc:db","root","root");
     //HttpSession ss=request.getSession();
     //String uid=(String)ss.getAttribute("id");
   con = DbConnection.connect("Select  * from Table_Student");
     ResultSet rs = con.executeQuery();
     while(rs.next())
     {
          String name = rs.getString("StudentName");
          int id = Integer.parseInt(rs.getString("sid"));
%>
          <option value=<%=id%>><%=name%></option>
<%
}
}catch(Exception e)
{    System.out.print(e);
}
%>
</span>
</li>
</select>

			
					<li id="li_1" >
		<label class="description" for="element_1">Username</label>
		<span>
			<input id="element_1_1" name= "Username_parent" type ="text" class="element text" >
			<label>*required</label>
			  
		</span>
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Password</label>
		<span>
			<input id="element_2_1" name="Password_parent" class="element text" type="password"> 
			<label for="element_2_1">*required</label>
		</span>
		 
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="1125809" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Add" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
</body>
</html>